#![feature(libc)]

use libc::size_t;

#[repr(C)]
pub struct ItemOptimizationData {
    pub ElementNo: u32,
    pub Today: u32,
    pub TheGrade: u8,
    pub TheFirstGrade: u8,
    pub LastRepetition: u32,
    pub OldInterval: u32,
    pub UsedInterval: u32,
    pub VirtualUsedInterval: u32,
    pub OI16: u32,
    pub NI16: u32,
    pub OI17: f64,
    pub NI17: f64,
    pub NewInterval: u32,
    pub Repetitions: u16,
    pub NewRepetitions: u16,
    pub Lapses: u16,
    pub NewLapses: u16,
    pub RequestedFI: u8,
    pub Ordinal: f64,
    pub AFactor: f64,
    pub NewAFactor: f64,
    pub UFactor: f64,
    pub NewUFactor: f64,
    pub OldRF: f64,
    pub NewRF: f64,
    pub OldOF: f64,
    pub NewOF: f64,
    pub Cases: u32,
    pub EstimatedFI: f64,
    pub ExpectedFI: f64,
    pub NormalizedGrade: f64,
    pub NGMin: f64,
    pub NGMax: f64,
    pub RepetitionsCategory: f64,
    pub RepetitionsHistory: u32,
    pub ExpR: f64,
    pub UsualR: f64,
    pub PredictedR: f64,
    pub Postpones: u32,
    pub _ItemDifficulty: f64,
}
